gg.jte.development-mode=true
spring.application.name=week8lab
spring.datasource.url=jdbc:mysql://cs3.calstatela.edu/cs3220stu21
spring.datasource.username=cs3220stu21
spring.datasource.password=fY1j5Biu77Oc
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update